unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind -n M-l select-pane -L
bind -n M-h select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U
